language: rust
rust:
  - stable
  - nightly
cache: cargo
env:
- MCU=stm32f103
- MCU=stm32f101
- MCU=stm32f100
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - rustup target add thumbv7m-none-eabi
  - cargo build --features=$MCU
